require:
  - rubocop-rails
  - rubocop-rspec


AllCops:
  TargetRubyVersion: 2.7.2
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/bundle

Style/Documentation:
  Enabled: false

Rails/FilePath:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/models/*
